name: Create signed git clone and image SBOMs

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate signed SBOM for repo content
        # Used after git clone at the beginning of the pipeline
        uses: scribe-security/action-bom@master
        with:
          target: 'git:.'
          scribe-enable: true
          components: packages,files,dep
          scribe-client-id: ${{ secrets.CLIENT_ID }}
          scribe-client-secret: ${{ secrets.CLIENT_SECRET }}
          format: attest

      - name: Build the Docker image
        # This is a stand-in step for whatever needs to happen in your pipeline culminating with building a docker image from the repository
        run: docker build . -t ${{ github.repository }}:${{ github.sha }}

      - name: Generate signed SBOM for docker image
        # Used after a docker image is built
        uses: scribe-security/action-bom@master
        with:
          target: 'docker:${{ github.repository }}:${{ github.sha }}'
          scribe-enable: true
          product-key: ${{ github.repository }}:${{ github.sha }}
          scribe-client-id: ${{ secrets.CLIENT_ID }}
          scribe-client-secret: ${{ secrets.CLIENT_SECRET }}
          format: attest

      - name: Generate SLSA provenance statement
        id: valint_slsa_statement
        uses: scribe-security/action-bom@master
        with:
          target: 'docker:${{ github.repository }}:${{ github.sha }}'
          format: statement-slsa

      - name: Upload SLSA provenance artifact
        uses: actions/upload-artifact@v3
        with:
          name: provenance
          path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
