name: Create signed git clone and image SBOMs

on: 
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Generate signed SBOM for repo content
        # Used after git clone at the beginning of the pipeline
        uses: scribe-security/action-bom@8f8a9ab1a5920ade414d4df102d7408f306a1570 # master
        with:
          target: 'git:.'
          scribe-enable: true
          components: packages,files,dep
          scribe-client-id: ${{ secrets.CLIENT_ID }}
          scribe-client-secret: ${{ secrets.CLIENT_SECRET }}
          format: attest

      - name: Build the Docker image
        # This is a stand-in step for whatever needs to happen in your pipeline culminating with building a docker image from the repository
        run: docker build . -t ${{ github.repository }}:${{ github.sha }}

      - name: Generate signed SBOM for docker image
        # Used after a docker image is built
        uses: scribe-security/action-bom@8f8a9ab1a5920ade414d4df102d7408f306a1570 # master
        with:
          target: 'docker:scribe-demo-product:${{ github.sha }}'
          scribe-enable: true
          product-key: ${{ github.repository }}:${{ github.sha }}
          scribe-client-id: ${{ secrets.CLIENT_ID }}
          scribe-client-secret: ${{ secrets.CLIENT_SECRET }}
          format: attest
