    name: Create signed git commit sbom

    on: push

    build:
        runs-on: ubuntu-latest

        permissions:
        id-token: write # workload identity access needed for signing using sigstore-github 

        steps:
        - uses: actions/checkout@v3

        - name: Generate signed git SBOM
        uses: scribe-security/action-bom@master
        with:
            target: 'git:.'
            scribe-enable: true
            product-key: ${{ github.repository }}
            scribe-client-id: ${{ secrets.CLIENT_ID }}
            scribe-client-secret: ${{ secrets.CLIENT_SECRET }}
            label: is_git_commit
            format: attest
            
